[build]
  publish = "public"
  command = "yarn run build"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    performance = 0.7
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9
    pwa = 0.8

[[plugins]]
  package = "netlify-purge-cloudflare-on-deploy"
